wordpressUsername: admin
wordpressPassword: adminpassword
wordpressEmail: admin@example.com

mysqlRootPassword: rootpassword
mysqlDatabase: wordpress
mysqlUser: wordpress
mysqlPassword: wordpresspassword
mysqlServiceName: mysql-service