apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    app: {{ template "wordpress.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wordpress.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "wordpress.name" . }}
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.mysqlServiceName }} 
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysqlUser }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysqlPassword }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysqlDatabase }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          emptyDir: {}

