apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "mysql.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysqlRootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysqlDatabase }}
            - name: MYSQL_USER
              value: {{ .Values.mysqlUser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysqlPassword }}
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}

