apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlServiceName }}
  labels:
    app: {{ template "mysql.name" . }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: {{ template "mysql.name" . }}