apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'   # Replace with your Kubernetes API server URL
    namespace: default                        # Replace with your target namespace
  project: default
  source:
    repoURL: 'https://github.com/Majid-dev/wordpress-chart-argocd.git'
    path: .
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
